server:
  port: 8400

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8300/eureka/

spring:
  application:
    name: zuulservice
#  profiles:
#    active:
#      default

logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes

zuul:
  routes:
    service-a:
      path: /s1/**
      serviceId: service-a
    service-b:
      path: /s2/**

      serviceId: service-b

#  ignored-services: service-a, service-b

#api:
#  service-a:
#    path: /s1/**
#  service-b:
#    path: /s2/**