server:
  port: 8400

#spring:
#  application:
#    name: zuul

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8400/eureka

#zuul:
#  routes:
#    service-1:
#      path: /test/**
#      stripPrefix: true



