server:
  port: 8300

spring:
  application:
    name: zuul

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka

#zuul:
#  routes:
#    service-1:
#      path: /test/**
#      stripPrefix: true



