server:
  port: 8400

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8300/eureka/

spring:
  application:
    name: zuulservice
  profiles:
    active:
      default

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes

zuul:
  ignored-services: service-a, service-b
  routes:
    service-a: /s1/**
    service-b: /s2/**