server:
  port: 8500

spring:
  application:
    name: service-2

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka