server:
  port: 8300

spring:
  application:
    name: zuulservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8300/eureka/

logging:
  level:
    com.netflix: DEBUG
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes

zuul:
  routes:
    service-a:
      path: /s1/**
      serviceId: service-a
    service-b:
      path: /s2/**

      serviceId: service-b