server:
  port: 8500

spring:
  application:
    name: service-a

#ribbon:
#  eureka:
#    enabled: true
#
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka